version: '2.7.0'
selector: rich_text_editor
simple_editor: true
body_class: yui-skin-sam
editor_extension_callbacks: "// MyExtension.install(editor);"
javascript_base_uri: //yui.yahooapis.com
editor_extension_javascripts:
  # - extension1.js
  # - extension2.js
additional_yui_javascripts:
  # - connection/connection
editor_config_javascript: "
{
  handleSubmit: true,
  autoHeight: true,
  dompath: false,
  collapse: true,
  toolbar: {
    collapse: true,
    titlebar: 'Text Editing Tools',
    draggable: false,
    buttonType: 'advanced',
    buttons: [
        { group: 'textstyle', label: 'Font Style',
            buttons: [
                { type: 'push', label: 'Bold CTRL + SHIFT + B', value: 'bold' },
                { type: 'push', label: 'Italic CTRL + SHIFT + I', value: 'italic' },
                { type: 'push', label: 'Underline CTRL + SHIFT + U', value: 'underline' },
            ]
        },
        { type: 'separator' },
        { group: 'alignment', label: 'Alignment',
            buttons: [
                { type: 'push', label: 'Align Left CTRL + SHIFT + [', value: 'justifyleft' },
                { type: 'push', label: 'Align Center CTRL + SHIFT + |', value: 'justifycenter' },
                { type: 'push', label: 'Align Right CTRL + SHIFT + ]', value: 'justifyright' },
                { type: 'push', label: 'Justify', value: 'justifyfull' }
            ]
        },
        { type: 'separator' },
        { group: 'insertitem', label: 'Insert',
            buttons: [
                { type: 'push', label: 'HTML Link CTRL + SHIFT + L', value: 'createlink', disabled: true },
                { type: 'push', label: 'Insert Image', value: 'insertimage' }
            ]
        }
    ]
  }
}"
